version: '2'
services:
  front:
    build: ./worlds
    environment:
      - NODE_ENV=development
    ports:
      - "8081:8080"
    volumes:
      - "./worlds:/app"
  back:
    build: ./worlds-server
    depends_on:
      - front
    environment:
      - FLASK_DEBUG=1
      - FLASK_ENV=development
      - WORLDS_FRONT=http://worlds_front_1:8080/
    links:
      - front
    ports:
      - "5000:5000"
    volumes:
      - "./worlds-server:/app"
      - "./config.py:/app/config.py"
      - "./media:/media"
      - "./log:/app/log"
  mail:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "1025:1025"
      - "8025:8025"
  db:
    build: ./db
    environment:
      - FLASK_DEBUG=1
      - FLASK_ENV=development
    links:
      - mail
    ports:
      - "5002:5000"
    volumes:
      - "./db:/app"
      - "./log:/app/log"
  blog:
    build: ./blog
    environment:
      - FLASK_DEBUG=1
      - FLASK_ENV=development
    links:
      - db
    ports:
      - "5001:5000"
    volumes:
      - "./blog:/app"
      - "./log:/app/log"
