"""followers

Revision ID: 71d900001ca7
Revises: e38cfa956238
Create Date: 2019-09-18 10:41:10.124691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71d900001ca7'
down_revision = 'e38cfa956238'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'followers',
        sa.Column('follower_id', sa.Integer(), nullable=True),
        sa.Column('followed_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['followed_id'], ['user.user_id'], ),
        sa.ForeignKeyConstraint(['follower_id'], ['user.user_id'], ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
