version: '3'
services:
  jenkins:
    image: jenkinsci/blueocean
    user: root
    ports:
      - 5060:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins/jenkins-data:/var/jenkins_home
      - ./jenkins/home:/home
      - ./:/home/worlds
